weaviate_version: 0.22.0
helm_version: 8.2.1
markdown: kramdown
kramdown:
    parse_block_html: false
rdiscount extensions: [smart]
collections:
    news:
        output: true
        permalink: /news/:path
    documentation:
        output: true
        permalink: /documentation/:path
    use_cases:
        output: true
        permalink: /use-cases/:path
    authors:
        output: true
exclude:
    - "console/*"
    - "*.json"
    - "Gemfile*"
    - "*.enc"
    - vendor
    - README.md
    - "*.draft"
    - js-src
    - node_modules
    - webpack.config.js
plugins:
    - jekyll-redirect-from
whitelist:
    - jekyll-redirect-from
docs:
    weaviate:
        - Get started
        - Setup
        - Weaviate Cluster Service
        - Add data
        - Query data
        - Features
        - Datasets
        - Client libs
        - More resources
        - About
    weaviate-cli:
        - Get started
        - Cluster
        - Schema
        - Misc